export const consumables = [
    {
      id: 1,
      name: "Formalin",
      category: "Histology",
      quantity: 10,
      unit: "Liters",
      description: "Used for tissue fixation.",
    },
    {
      id: 2,
      name: "Xylene",
      category: "Histology",
      quantity: 15,
      unit: "Liters",
      description: "Used for tissue clearing.",
    },
    {
      id: 3,
      name: "Ethanol (Absolute)",
      category: "Histology",
      quantity: 20,
      unit: "Liters",
      description: "Used for tissue dehydration.",
    },
    {
      id: 4,
      name: "Hematoxylin",
      category: "Histology",
      quantity: 5,
      unit: "Bottles",
      description: "Primary stain for nuclei in histological slides.",
    },
    {
      id: 5,
      name: "Eosin",
      category: "Histology",
      quantity: 5,
      unit: "Bottles",
      description: "Counterstain for cytoplasm and other components.",
    },
    {
      id: 6,
      name: "Cytology Brushes",
      category: "Cytology",
      quantity: 50,
      unit: "Pieces",
      description: "Used for collecting cytological samples.",
    },
    {
      id: 7,
      name: "Papanicolaou Stain",
      category: "Cytology",
      quantity: 10,
      unit: "Kits",
      description: "Stain used in Pap smears.",
    },
    {
      id: 8,
      name: "Cytology Fixative Spray",
      category: "Cytology",
      quantity: 20,
      unit: "Cans",
      description: "Fixative for cytology smears.",
    },
    {
      id: 9,
      name: "Glass Slides",
      category: "Common",
      quantity: 500,
      unit: "Pieces",
      description: "Used for mounting tissue and cytology samples.",
    },
    {
      id: 10,
      name: "Cover Slips",
      category: "Common",
      quantity: 1000,
      unit: "Pieces",
      description: "Used to cover mounted specimens on slides.",
    },
    {
      id: 11,
      name: "Immersion Oil",
      category: "Common",
      quantity: 10,
      unit: "Bottles",
      description: "Used for microscopy to improve resolution.",
    },
    {
      id: 12,
      name: "Microscope Lens Cleaning Paper",
      category: "Common",
      quantity: 200,
      unit: "Sheets",
      description: "Used for cleaning microscope lenses.",
    },
  ];
  